### ISSUE TITLE
faraday-zipkin not thread-safe?!

### ISSUE THREAD

**Issue by phrinx** [Oscil8/faraday-zipkin#3]
I ran into a error which indicates that this gem is not thread-safe. The source of the problem however seems to be inside finagle-thrift which is using a global rather than a thread-local stack:

```
undefined method `trace_id' for nil:NilClass

Stacktrace (most recent call first):

  faraday-zipkin/trace_headers.rb:32:in `call'
    env[:request_headers][header] = ::Trace.id.send(method).to_s
  org/jruby/RubyHash.java:1341:in `each'
  faraday-zipkin/trace_headers.rb:31:in `call'
    B3_HEADERS.each do |method, header|
  finagle-thrift/trace.rb:34:in `unwind'
    yield
  finagle-thrift/trace.rb:32:in `unwind'
    begin
  faraday-zipkin/trace_headers.rb:28:in `call'
    ::Trace.unwind do
  faraday/rack_builder.rb:139:in `build_response'
    app.call(build_env(connection, request))
  faraday/connection.rb:377:in `run_request'
    builder.build_response(self, request)
  elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
    ( body ? __convert_to_json(body) : nil ),
  org/jruby/RubyProc.java:271:in `call'
  elasticsearch/transport/transport/base.rb:187:in `perform_request'
    response   = block.call(connection, url)
  elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    super do |connection, url|
  elasticsearch/transport/client.rb:115:in `perform_request'
    transport.perform_request method, path, params, body
  elasticsearch/api/namespace/common.rb:21:in `perform_request'
    client.perform_request method, path, params, body
  elasticsearch/api/actions/cluster/health.rb:49:in `health'
    perform_request(method, path, params, body).body
  ...
```

https://github.com/lookout/zipkin/issues/18 is also related to this issue.

**Comment by Oscil8** [comment]
This is an issue with an upstream dependency; there's no way to fix the thread safety issue here, but we can catch exceptions at least. Unfortunately, that may just hide the issue without a place to drop logs.
